#! /usr/bin/env bash
set -euo pipefail

inputs=()
valid_inputs=()
output=""

usage()
{
    cat <<EOF_USAGE
usage:
  $0 --input FILE [FILE ...] [--input FILE ...] --output FILE

options:
  --input, -i FILE      calibration fragment(s) to merge; may be repeated
  --output, -o FILE     merged calibration output file
  --help, -h            show this help message

example:
  $0 \
    --input dcalib.fifo_0.conf dcalib.fifo_1.conf \
    --output calibration.merged.conf
EOF_USAGE
}

fail()
{
    echo "ERROR: $*" >&2
    echo >&2
    usage >&2
    exit 1
}

while [ $# -gt 0 ]; do
    case "$1" in
        --input|-i)
            shift
            [ $# -ge 1 ] || fail "--input requires at least one FILE"
            while [ $# -gt 0 ]; do
                case "$1" in
                    --*|-*) break ;;
                    *) inputs+=("$1"); shift ;;
                esac
            done
            ;;
        --output|-o)
            [ $# -ge 2 ] || fail "$1 requires FILE"
            output=$2
            shift 2
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            fail "unknown option: $1"
            ;;
    esac
done

[ ${#inputs[@]} -gt 0 ] || fail "at least one --input FILE is required"
[ -n "${output}" ] || fail "missing --output FILE"

for input in "${inputs[@]}"; do
    if [ ! -f "${input}" ]; then
        echo "WARNING: input file does not exist, skipping: ${input}" >&2
        continue
    fi
    valid_inputs+=("${input}")
done

[ ${#valid_inputs[@]} -gt 0 ] || fail "no existing input files to merge"

awk '
function print_section_header(section) {
    if (nprinted > 0)
        print ""

    print "[" section "]"
    if (section == "TDC")
        print "# device fifo column pixel tdc off iif"
    else if (section == "CHANNEL")
        print "# device fifo column pixel offset"
    else if (section == "TRIGGER")
        print "# device fifo offset"

    ++nprinted
}

function save_row(section, row) {
    rows[section, ++nrows[section]] = row
}

END {
    print "# merged calibration file"
    print "# generated by merge_calibration_file.sh"

    for (section_index = 1; section_index <= 3; ++section_index) {
        section = section_names[section_index]
        if (nrows[section] == 0)
            continue
        print_section_header(section)
        for (row_index = 1; row_index <= nrows[section]; ++row_index)
            print rows[section, row_index]
    }
}

BEGIN {
    current = ""
    nprinted = 0
    section_names[1] = "TDC"
    section_names[2] = "CHANNEL"
    section_names[3] = "TRIGGER"
}

FNR == 1 {
    current = ""
}

/^[[:space:]]*$/ {
    next
}

/^[[:space:]]*#/ {
    next
}

/^\[[^]]+\][[:space:]]*$/ {
    current = $0
    gsub(/^\[/, "", current)
    gsub(/\][[:space:]]*$/, "", current)
    if (current != "TDC" && current != "CHANNEL" && current != "TRIGGER") {
        printf("ERROR: unsupported section [%s] in %s line %d\n", current, FILENAME, FNR) > "/dev/stderr"
        exit 2
    }
    next
}

{
    if (current == "") {
        printf("ERROR: calibration row before section header in %s line %d\n", FILENAME, FNR) > "/dev/stderr"
        exit 2
    }
    save_row(current, $0)
}
' "${valid_inputs[@]}" > "${output}.tmp"

mv "${output}.tmp" "${output}"
echo "merged ${#valid_inputs[@]} input files into ${output}"
