#! /usr/bin/env bash
set -euo pipefail

inputs=()
output=""

usage()
{
    cat <<EOF_USAGE
usage:
  $0 --input FILE [--input FILE ...] --output FILE

options:
  --input, -i FILE      calibration fragment to merge; may be repeated
  --output, -o FILE     merged calibration output file
  --help, -h            show this help message

example:
  $0 \
    --input dcalib.fifo_0.conf \
    --input dcalib.fifo_1.conf \
    --output calibration.merged.conf
EOF_USAGE
}

fail()
{
    echo "ERROR: $*" >&2
    echo >&2
    usage >&2
    exit 1
}

while [ $# -gt 0 ]; do
    case "$1" in
        --input|-i)
            [ $# -ge 2 ] || fail "$1 requires FILE"
            inputs+=("$2")
            shift 2
            ;;
        --output|-o)
            [ $# -ge 2 ] || fail "$1 requires FILE"
            output=$2
            shift 2
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            fail "unknown option: $1"
            ;;
    esac
done

[ ${#inputs[@]} -gt 0 ] || fail "at least one --input FILE is required"
[ -n "${output}" ] || fail "missing --output FILE"

for input in "${inputs[@]}"; do
    [ -f "${input}" ] || fail "input file does not exist: ${input}"
done

awk '
function print_section_header(section) {
    if (printed[section])
        return

    if (nprinted > 0)
        print ""

    print "[" section "]"
    if (section == "TDC")
        print "# device fifo column pixel tdc off iif"
    else if (section == "CHANNEL")
        print "# device fifo column pixel offset"
    else if (section == "TRIGGER")
        print "# device fifo offset"

    printed[section] = 1
    ++nprinted
}

BEGIN {
    current = ""
    nprinted = 0
    print "# merged calibration file"
    print "# generated by merge_calibration_file.sh"
}

FNR == 1 {
    current = ""
}

/^[[:space:]]*$/ {
    next
}

/^[[:space:]]*#/ {
    next
}

/^\[[^]]+\][[:space:]]*$/ {
    current = $0
    gsub(/^\[/, "", current)
    gsub(/\][[:space:]]*$/, "", current)
    if (current != "TDC" && current != "CHANNEL" && current != "TRIGGER") {
        printf("ERROR: unsupported section [%s] in %s line %d\n", current, FILENAME, FNR) > "/dev/stderr"
        exit 2
    }
    next
}

{
    if (current == "") {
        printf("ERROR: calibration row before section header in %s line %d\n", FILENAME, FNR) > "/dev/stderr"
        exit 2
    }
    print_section_header(current)
    print $0
}
' "${inputs[@]}" > "${output}.tmp"

mv "${output}.tmp" "${output}"
echo "merged ${#inputs[@]} input files into ${output}"
