#include <TFile.h>
#include <TH2.h>

#include <fstream>
#include <iostream>
#include <string>
#include <vector>

void
clock_transition(const std::string &infilename,
                 const std::string &run,
                 int device,
                 int fifo,
                 const std::string &outfilename = "clock_transition.root",
                 const std::string &conffilename = "clock-corrections.conf")
{
  auto fin = TFile::Open(infilename.c_str(), "READ");
  auto hin = fin ? (TH2 *)fin->Get("hDeltaT_spill") : nullptr;
  if (!hin) {
    std::cerr << "ERROR: could not open hDeltaT_spill in " << infilename << std::endl;
    return;
  }

  std::vector<double> means(hin->GetNbinsX(), 0.);
  std::vector<double> weights(hin->GetNbinsX(), 0.);
  for (int ix = 1; ix <= hin->GetNbinsX(); ++ix) {
    for (int iy = 1; iy <= hin->GetNbinsY(); ++iy) {
      double y = hin->GetYaxis()->GetBinCenter(iy);
      if (y < -2. || y > 2.)
        continue;
      double w = hin->GetBinContent(ix, iy);
      means[ix - 1] += w * y;
      weights[ix - 1] += w;
    }
    if (weights[ix - 1] > 0.)
      means[ix - 1] /= weights[ix - 1];
  }

  double high_sum = 0., high_weight = 0.;
  double low_sum = 0., low_weight = 0.;
  for (int i = 0; i < hin->GetNbinsX(); ++i) {
    if (weights[i] <= 0.)
      continue;
    if (means[i] > -0.2) {
      high_sum += weights[i] * means[i];
      high_weight += weights[i];
    } else {
      low_sum += weights[i] * means[i];
      low_weight += weights[i];
    }
  }
  double high_mean = high_sum / high_weight;
  double low_mean = low_sum / low_weight;
  double threshold = 0.5 * (high_mean + low_mean);

  auto fout = TFile::Open(outfilename.c_str(), "RECREATE");
  auto hout = (TH2 *)hin->Clone("hDeltaT_spill_aligned");
  hout->SetTitle("spill-aligned delta-t;spill;delta-t");
  hout->Reset("ICES");

  std::vector<int> corrected_spills;
  for (int ix = 1; ix <= hin->GetNbinsX(); ++ix) {
    if (weights[ix - 1] <= 0.)
      continue;
    bool low_state = means[ix - 1] < threshold;
    int shift = low_state ? 1 : 0;
    if (low_state)
      corrected_spills.push_back(ix - 1);

    for (int iy = 1; iy <= hin->GetNbinsY(); ++iy) {
      double content = hin->GetBinContent(ix, iy);
      if (content == 0.)
        continue;
      double y = hin->GetYaxis()->GetBinCenter(iy) + shift;
      int aligned_bin = hout->GetYaxis()->FindBin(y);
      if (aligned_bin < 1 || aligned_bin > hout->GetNbinsY())
        continue;
      hout->AddBinContent(ix, aligned_bin, content);
      double old_error = hout->GetBinError(ix, aligned_bin);
      double error = hin->GetBinError(ix, iy);
      hout->SetBinError(ix, aligned_bin,
                        TMath::Sqrt(old_error * old_error + error * error));
    }
  }

  hin->Write("hDeltaT_spill");
  hout->Write();
  fout->Close();

  std::ofstream conf(conffilename);
  conf << "# Spill-specific clock corrections generated by clock_transition.C\n"
       << "# correction convention: corrected_time = calibrated_time - correction\n"
       << "[CLOCK]\n"
       << "# run device fifo correction spill...\n";
  if (!corrected_spills.empty()) {
    conf << run << ' ' << device << ' ' << fifo << " -1";
    for (int spill : corrected_spills)
      conf << ' ' << spill;
    conf << '\n';
  }
  conf.close();

  std::cout << "low-state mean:  " << low_mean << std::endl;
  std::cout << "high-state mean: " << high_mean << std::endl;
  std::cout << "threshold:       " << threshold << std::endl;
  std::cout << "corrected spills: " << corrected_spills.size() << std::endl;
  std::cout << "output:           " << outfilename << std::endl;
  std::cout << "clock config:     " << conffilename << std::endl;
}
