# Finger-scintillator coincidence trigger.
# The DAQ trigger tag on device 200, FIFO 32 represents the AND of the finger scintillators.

selector TRIGGER {
    type        = 9
    device      = 200
    fifo        = 32
}

trigger {
    seed TRIGGER
}
