# Explicit frame_center example: center the normal frame window 35 clocks after event time.
selector TRIGGER {
    type        = 9
    device      = 200
    fifo        = 32
    column      = *
    pixel       = *
    time_offset = 0.
}

selector DETECTOR {
    type        = 1
    device      = 201
    fifo        = *
    column      = *
    pixel       = *
    time_offset = 0.
}

trigger {
    seed TRIGGER
    frame_center DETECTOR
}
