# Specific seed, multiplicity, negative-time requirement, veto, and explicit frame centering.
selector TRIGGER {
    type        = 9
    device      = 200
    fifo        = 32
    column      = *
    pixel       = *
    time_offset = 0.
}

selector DETECTOR {
    type        = 1
    device      = 201
    fifo        = *
    column      = *
    pixel       = *
    time_offset = 0.
}

selector EARLY {
    type        = 1
    device      = 194
    fifo        = 7
    column      = *
    pixel       = *
    time_offset = 0.
}

selector VETO {
    type        = 9
    time_offset = 0.
}

trigger {
    seed TRIGGER
    frame_center DETECTOR

    require DETECTOR {
        dt  = [-8,+8]
        min = 2
    }

    require EARLY {
        dt  = [-30,0]
        min = 1
    }

    veto VETO {
        dt = [-100,+100]
    }
}
