# Delayed trigger tag plus TIMING coincidence.
# event_time = raw_trigger_time - 110.
selector TRIGGER {
    type        = 9
    device      = 200
    fifo        = 32
    column      = *
    pixel       = *
    time_offset = 0.
}

selector TIMING {
    type        = 1
    device      = 200
    fifo        = [0,7]
    column      = *
    pixel       = *
    time_offset = 0.
}

trigger {
    seed TRIGGER

    require TIMING {
        dt  = [-10,+10]
        min = 32
    }
}
