# Self-trigger coincidence: require at least 32 distinct channels.
# A channel is the tuple (device,fifo,column,pixel).
selector TIMING {
    type        = 1
    device      = 200
    fifo        = [0,7]
    column      = *
    pixel       = *
    time_offset = 0.
}

trigger {

    coincidence TIMING {
        dt      = [-10,+10]
        min     = 32
        unique  = channel
    }

}
