# Specific seed and multiplicity requirement anywhere on a second FIFO.
selector A {
    type        = 1
    device      = 192
    fifo        = 3
    column      = 1
    pixel       = 12
    time_offset = 0.
}

selector MULT {
    type        = 1
    device      = 193
    fifo        = 5
    column      = *
    pixel       = *
    time_offset = 0.
}

trigger {
    seed A

    require MULT {
        dt  = [-20,+20]
        min = 3
    }
}
