# Explicit set selector: only FIFOs 0, 2, 4 and 6 match TIMING.
selector TRIGGER {
    type        = 9
    device      = 200
    fifo        = 32
    column      = *
    pixel       = *
    time_offset = 0.
}

selector TIMING {
    type        = 1
    device      = 200
    fifo        = {0,2,4,6}
    column      = *
    pixel       = *
    time_offset = 0.
}

trigger {
    seed TRIGGER

    require TIMING {
        dt  = [-10,+10]
        min = 20
    }
}
