# SPS IRT geometry fit parameters.
# parameter                 start             min               max               status
# Angles are radians; positions are millimetres.
# The SPS fit assumes no rotation around the X axis.

assembly_rotation_x         0.0             -0.1               0.1               free
assembly_rotation_y        -0.081479300    -0.2               0.2               free
assembly_rotation_x_pivot_y 0.0            -500.0             500.0               fixed
assembly_rotation_x_pivot_z 2500.0         1500.0            3500.0               fixed
emission_z                 2534.0            2300.0            2700.0             fixed

mirror_delta_x               0.0             -100.0             100.0              fixed
mirror_delta_y               0.0             -100.0             100.0              fixed
mirror_delta_z               0.0             -100.0             100.0              fixed
mirror_delta_r               0.0            -100.0             100.0               fixed
mirror_rotation_x            0.00690688     -0.1               0.1                free
mirror_rotation_y           -0.00328221     -0.1               0.1                free
mirror_rotation_z            0.0             -0.01              0.01               fixed

detector_delta_x             0.0             -100.0             100.0              fixed
detector_delta_y             0.0             -100.0             100.0              fixed
detector_delta_z             0.0             -100.0             100.0              fixed
detector_delta_theta        -6.76810e-07     -0.2                0.2               fixed
detector_delta_phi          -6.87153e-07     -0.1                0.1               fixed
detector_rotation_x          0.0             -0.1                0.1               fixed
detector_rotation_y          0.0             -0.3                0.3               fixed
detector_rotation_z          0.0             -0.1                0.1               fixed

# Expected Cherenkov angle in radians.
expected_cherenkov_angle     0.039979159      0.03               0.05              fixed
